const { db, COLLECTIONS, generateTimestamp } = require("./config");

// UNIFIED ID SYSTEM: Use Firestore auto-generated IDs instead of custom generation
// This ensures consistency with the Flutter app and Cloud Functions

// Documents data - restored default document metadata entries
const documentsData = [
  {
    // ID will be auto-generated by Firestore for consistency
    fileName: "Surat_Masuk_001.pdf",
    fileSize: 1024576, // 1MB
    fileType: "pdf",
    filePath: "documents/surat-masuk/Surat_Masuk_001.pdf",
    uploadedBy: "admin-uid-001", // Will be replaced with actual admin UID
    uploadedAt: generateTimestamp(10), // 10 days ago
    category: "surat-masuk",
    permissions: ["admin-uid-001", "user1-uid-002"],
    isActive: true,
    metadata: {
      description: "Contoh surat masuk untuk kategori surat masuk",
      tags: ["surat", "masuk", "sample"],
      version: "1.0",
      contentType: "application/pdf",
      downloadUrl: null
    }
  },
  {
    // ID will be auto-generated by Firestore for consistency
    fileName: "SK_Kebijakan_001.pdf",
    fileSize: 2048576, // 2MB
    fileType: "pdf",
    filePath: "documents/surat-keputusan/SK_Kebijakan_001.pdf",
    uploadedBy: "admin-uid-001", // Will be replaced with actual admin UID
    uploadedAt: generateTimestamp(8), // 8 days ago
    category: "surat-keputusan",
    permissions: ["admin-uid-001", "user1-uid-002"],
    isActive: true,
    metadata: {
      description: "Contoh surat keputusan untuk kategori surat keputusan",
      tags: ["surat", "keputusan", "kebijakan"],
      version: "1.0",
      contentType: "application/pdf",
      downloadUrl: null
    }
  },
  {
    // ID will be auto-generated by Firestore for consistency
    fileName: "Notulen_Rapat_001.pdf",
    fileSize: 1536576, // 1.5MB
    fileType: "pdf",
    filePath: "documents/notulen-rapat/Notulen_Rapat_001.pdf",
    uploadedBy: "admin-uid-001", // Will be replaced with actual admin UID
    uploadedAt: generateTimestamp(6), // 6 days ago
    category: "notulen-rapat",
    permissions: ["admin-uid-001", "user1-uid-002"],
    isActive: true,
    metadata: {
      description: "Contoh notulen rapat untuk kategori notulen rapat",
      tags: ["notulen", "rapat", "meeting"],
      version: "1.0",
      contentType: "application/pdf",
      downloadUrl: null
    }
  },
  {
    // ID will be auto-generated by Firestore for consistency
    fileName: "Laporan_Evaluasi_001.pdf",
    fileSize: 3072576, // 3MB
    fileType: "pdf",
    filePath: "documents/laporan-evaluasi/Laporan_Evaluasi_001.pdf",
    uploadedBy: "admin-uid-001", // Will be replaced with actual admin UID
    uploadedAt: generateTimestamp(4), // 4 days ago
    category: "laporan-evaluasi",
    permissions: ["admin-uid-001", "user1-uid-002"],
    isActive: true,
    metadata: {
      description: "Contoh laporan evaluasi untuk kategori laporan evaluasi",
      tags: ["laporan", "evaluasi", "monitoring"],
      version: "1.0",
      contentType: "application/pdf",
      downloadUrl: null
    }
  }
];

async function seedDocuments() {
  console.log("🚀 Starting documents seeding...");

  try {
    // Check if there are any documents to seed
    if (documentsData.length === 0) {
      console.log("ℹ️ No default documents to seed. Document-metadata collection will remain empty.");
      console.log("💡 Add documents to the documentsData array if you want to seed default document metadata.");
      return;
    }

    // Get actual user UIDs from users collection
    const usersSnapshot = await db.collection(COLLECTIONS.USERS).get();
    const userMap = {};

    usersSnapshot.docs.forEach(doc => {
      const userData = doc.data();
      if (userData.email === 'admin@simdoc.com') {
        userMap['admin-uid-001'] = doc.id;
      } else if (userData.email === 'user1@simdoc.com') {
        userMap['user1-uid-002'] = doc.id;
      } else if (userData.email === 'user2@simdoc.com') {
        userMap['user2-uid-003'] = doc.id;
      } else if (userData.email === 'user3@simdoc.com') {
        userMap['user3-uid-004'] = doc.id;
      }
    });

    console.log("📋 Found users:", Object.keys(userMap).length);

    const batch = db.batch();

    for (const document of documentsData) {
      // UNIFIED ID SYSTEM: Use Firestore auto-generated ID
      const docRef = db.collection(COLLECTIONS.DOCUMENTS).doc(); // Auto-generate ID
      const documentId = docRef.id; // Get the auto-generated ID

      // Add the ID to the document data for consistency
      const docData = {
        ...document,
        id: documentId, // Store ID in document for consistency
      };

      // Replace placeholder UIDs with actual UIDs
      if (userMap[docData.uploadedBy]) {
        docData.uploadedBy = userMap[docData.uploadedBy];
      }

      // Replace placeholder UIDs in permissions array
      docData.permissions = docData.permissions.map(uid =>
        userMap[uid] || uid
      );

      // Add unified ID system metadata
      docData.metadata = {
        ...docData.metadata,
        createdBy: "database_seeder",
        unifiedIdSystem: true, // Mark as using unified ID system
        seederVersion: "2.0",
        seedTimestamp: new Date().toISOString(),
      };

      batch.set(docRef, docData);
      console.log(`📝 Prepared document: ${docData.fileName} with ID: ${documentId}`);
    }

    await batch.commit();
    console.log("✅ Documents collection seeded successfully!");
    console.log(`📊 Total documents created: ${documentsData.length}`);

    // Display documents summary by category and status
    const categoryCount = documentsData.reduce((acc, doc) => {
      acc[doc.category] = (acc[doc.category] || 0) + 1;
      return acc;
    }, {});

    const activeCount = documentsData.filter(doc => doc.isActive).length;
    const inactiveCount = documentsData.filter(doc => !doc.isActive).length;

    console.log("\n📋 Documents Summary:");
    console.log(`  ✅ Active documents: ${activeCount}`);
    console.log(`  ❌ Inactive documents: ${inactiveCount}`);

    console.log("\n📂 Documents by Category:");
    Object.entries(categoryCount).forEach(([category, count]) => {
      console.log(`  📁 ${category}: ${count} documents`);
    });

    console.log("\n📄 Sample Documents Created:");
    documentsData.slice(0, 3).forEach(doc => {
      console.log(`  📄 ${doc.fileName} (${doc.category})`);
    });

    console.log("🆔 All documents use unified ID system (Firestore auto-generated IDs)");

  } catch (error) {
    console.error("❌ Error seeding documents:", error);
    throw error;
  }
}

// Run if called directly
if (require.main === module) {
  seedDocuments()
    .then(() => {
      console.log("🎉 Documents seeding completed!");
      process.exit(0);
    })
    .catch((error) => {
      console.error("💥 Documents seeding failed:", error);
      process.exit(1);
    });
}

module.exports = { seedDocuments, documentsData };
