// Mocks generated by Mockito 5.4.6 from annotations
// in managementdoc/test/unit/bloc/upload_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cross_file/cross_file.dart' as _i5;
import 'package:managementdoc/features/upload/models/upload_file_model.dart'
    as _i4;
import 'package:managementdoc/features/upload/repositories/upload_repository.dart'
    as _i2;
import 'package:managementdoc/models/upload_result_model.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UploadRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadRepository extends _i1.Mock implements _i2.UploadRepository {
  MockUploadRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isUploading =>
      (super.noSuchMethod(Invocation.getter(#isUploading), returnValue: false)
          as bool);

  @override
  _i3.Future<List<_i4.UploadFileModel>> addFilesToQueue(
    List<_i5.XFile>? files, {
    String? categoryId,
    Map<String, String>? customMetadata,
    bool? checkDuplicates = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addFilesToQueue,
              [files],
              {
                #categoryId: categoryId,
                #customMetadata: customMetadata,
                #checkDuplicates: checkDuplicates,
              },
            ),
            returnValue: _i3.Future<List<_i4.UploadFileModel>>.value(
              <_i4.UploadFileModel>[],
            ),
          )
          as _i3.Future<List<_i4.UploadFileModel>>);

  @override
  _i3.Future<void> startUpload() =>
      (super.noSuchMethod(
            Invocation.method(#startUpload, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> pauseUpload(String? fileId) =>
      (super.noSuchMethod(
            Invocation.method(#pauseUpload, [fileId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> resumeUpload(String? fileId) =>
      (super.noSuchMethod(
            Invocation.method(#resumeUpload, [fileId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelUpload(String? fileId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelUpload, [fileId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> retryUpload(String? fileId) =>
      (super.noSuchMethod(
            Invocation.method(#retryUpload, [fileId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeFromQueue(String? fileId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromQueue, [fileId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearQueue() =>
      (super.noSuchMethod(
            Invocation.method(#clearQueue, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  List<_i4.UploadFileModel> getUploadQueue() =>
      (super.noSuchMethod(
            Invocation.method(#getUploadQueue, []),
            returnValue: <_i4.UploadFileModel>[],
          )
          as List<_i4.UploadFileModel>);

  @override
  _i3.Stream<double> getUploadProgress(String? fileId) =>
      (super.noSuchMethod(
            Invocation.method(#getUploadProgress, [fileId]),
            returnValue: _i3.Stream<double>.empty(),
          )
          as _i3.Stream<double>);

  @override
  _i3.Stream<double> getOverallProgress() =>
      (super.noSuchMethod(
            Invocation.method(#getOverallProgress, []),
            returnValue: _i3.Stream<double>.empty(),
          )
          as _i3.Stream<double>);

  @override
  _i3.Stream<_i4.UploadStatus> getUploadStatus(String? fileId) =>
      (super.noSuchMethod(
            Invocation.method(#getUploadStatus, [fileId]),
            returnValue: _i3.Stream<_i4.UploadStatus>.empty(),
          )
          as _i3.Stream<_i4.UploadStatus>);

  @override
  Map<String, dynamic> getUploadStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#getUploadStatistics, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i3.Future<List<String>> validateFiles(List<_i5.XFile>? files) =>
      (super.noSuchMethod(
            Invocation.method(#validateFiles, [files]),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> checkForDuplicates(
    List<_i4.UploadFileModel>? files,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkForDuplicates, [files]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  void updateSettings({
    int? maxConcurrentUploads,
    int? chunkSize,
    int? retryAttempts,
  }) => super.noSuchMethod(
    Invocation.method(#updateSettings, [], {
      #maxConcurrentUploads: maxConcurrentUploads,
      #chunkSize: chunkSize,
      #retryAttempts: retryAttempts,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<List<_i6.UploadResult>> uploadFiles(
    List<_i4.UploadFileModel>? files,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFiles, [files]),
            returnValue: _i3.Future<List<_i6.UploadResult>>.value(
              <_i6.UploadResult>[],
            ),
          )
          as _i3.Future<List<_i6.UploadResult>>);

  @override
  _i3.Future<List<_i6.UploadResult>> uploadFilesWithProgress(
    List<_i4.UploadFileModel>? files,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFilesWithProgress, [files]),
            returnValue: _i3.Future<List<_i6.UploadResult>>.value(
              <_i6.UploadResult>[],
            ),
          )
          as _i3.Future<List<_i6.UploadResult>>);

  @override
  _i3.Future<List<_i6.UploadResult>> retryFailedUploads(
    List<_i4.UploadFileModel>? failedFiles,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#retryFailedUploads, [failedFiles]),
            returnValue: _i3.Future<List<_i6.UploadResult>>.value(
              <_i6.UploadResult>[],
            ),
          )
          as _i3.Future<List<_i6.UploadResult>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
